### ISSUE TITLE
Focus lost on click

### ISSUE THREAD

**Issue by mdeweerd** [quentint/long-press#16]
At least on
http://toki-woki.net/lab/long-press/,
when selecting the character from the list by clicking on it, focus in the original edit field is lost.
Ideally, focus should be regained after the click.

**Comment by amoludage** [comment]
@mdeweerd I didn't understand this issue, because I have tried this and edit field focus does not lost for me.
Can you provide more details regarding to this issue.

Thanks.

**Comment by mdeweerd** [comment]
Hi
I must say I had forgotten about his report ;-).

To reproduce it:
a) click inside the text box.
b) Press and hold 'e'
c) While holding 'e', use the mouse to select any of the special characters shown.
d) Release 'e'.
e) When you try to continue to type nothing appears in the text box because the text box focus is lost.

Tried on: Google Chrome, Microsoft Edge (Win10).

**Comment by amoludage** [comment]
@mdeweerd Thanks, I have tried this, when mouse hover on special characters it automatically selected into edit field, no need to click on special characters to select. But problem is when we hover and click on the special characters then text box focus is lost.

@quentint is this issue??

**Comment by quentint** [comment]
Not really an "issue", but could be fixed :)

**Comment by mdeweerd** [comment]
Very old ticket - no longer expecting this to be implemented.
