### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by dhunink** [quentint/long-press#19]
I've tested the wonderful jquery plugin on https://topografieindeklas.nl/topotrainer/nederland/ Works perfect in Safari and Firefox, but doesn't work on Chrome. Is that a known issue?

**Comment by amoludage** [comment]
@quentint @dhunink I'm using Chrome Version 46.0.2490.86 (64-bit) on Ubuntu 14.04 OS, and this is working for me.

**Comment by quentint** [comment]
This is a non-issue, Mac has its own character selector (see the screenshot he attached).
